PRODUCT_ALIASES = {
    "zoom-phone": {
        "name": "Zoom Phone",
        "aliases": [
            "Zoom Phone",
            "Phone System Management",
            "phone user",
            "phone users",
            "call queue",
            "call queues",
            "auto receptionist",
            "IVR",
            "shared line group",
            "direct phone number",
            "emergency address",
            "desk phone",
            "phone policy",
            "Zoom Phone policy",
            "common area phone",
            "call delegation",
            "phone site",
            "phone number management",
        ],
        "strong_signals": [
            "zoom phone",
            "phone system management",
            "phone user",
            "call queue",
            "auto receptionist",
            "shared line group",
            "common area phone",
            "call delegation",
            "phone site",
            "phone number",
        ],
        "medium_signals": [
            "phone users",
            "call queues",
            "direct numbers",
            "ivr",
            "emergency address",
            "desk phone",
            "phone policy",
            "phone site",
        ],
        "weak_signals": [
            "calling",
            "phone",
            "device",
            "extension",
            "desk phone",
            "dial",
            "voicemail",
            "phone number",
        ],
        "negative_signals": [
            "zoom meetings",
            "zoom rooms",
            "zoom contact center",
            "zoom webinar",
            "team chat",
            "whiteboard",
            "zoom clips",
            "zoom scheduler",
        ],
    },
    "zoom-contact-center": {
        "name": "Zoom Contact Center",
        "aliases": [
            "Zoom Contact Center",
            "Contact Center",
            "contact center agent",
            "contact center supervisor",
            "contact center admin",
            "queue routing",
            "skill-based routing",
            "omnichannel",
            "voice engagement",
            "web chat",
            "SMS channel",
            "video engagement",
            "contact center dashboard",
            "wallboard",
            "workforce management",
            "quality management",
            "screen recording",
            "call recording",
        ],
        "strong_signals": [
            "zoom contact center",
            "contact center agent",
            "contact center supervisor",
            "skill-based routing",
            "omnichannel engagement",
            "queue routing",
            "wallboard",
            "workforce management",
            "quality management",
        ],
        "medium_signals": [
            "contact center",
            "web chat",
            "sms channel",
            "video engagement",
            "voice engagement",
            "screen recording",
            "call recording",
            "contact center dashboard",
            "agent status",
        ],
        "weak_signals": [
            "agent",
            "queue",
            "routing",
            "engagement",
            "supervisor",
            "omnichannel",
        ],
        "negative_signals": [
            "zoom phone",
            "zoom meetings",
            "zoom rooms",
            "zoom webinar",
            "zoom clips",
        ],
    },
    "zoom-clips": {
        "name": "Zoom Clips",
        "aliases": [
            "Zoom Clips",
            "video clip",
            "video clips",
            "screen recording",
            "clip sharing",
            "clip library",
            "clip editing",
            "clip trimming",
            "clip viewer",
            "clip analytics",
            "clip comments",
            "clip transcription",
        ],
        "strong_signals": [
            "zoom clips",
            "video clip",
            "clip library",
            "clip sharing",
            "clip editing",
            "clip trimming",
            "clip viewer",
        ],
        "medium_signals": [
            "clip analytics",
            "clip comments",
            "clip transcription",
            "screen recording",
            "video clips",
        ],
        "weak_signals": [
            "clip",
            "clips",
            "recording",
            "video message",
        ],
        "negative_signals": [
            "zoom phone",
            "zoom meetings",
            "zoom contact center",
            "zoom rooms",
            "zoom webinar",
        ],
    },
    "zoom-meetings": {
        "name": "Zoom Meetings",
        "aliases": [
            "Zoom Meetings",
            "Zoom Meeting",
            "meeting host",
            "meeting participant",
            "meeting scheduling",
            "meeting recording",
            "meeting chat",
            "breakout rooms",
            "meeting polls",
            "meeting reactions",
            "meeting security",
            "waiting room",
            "meeting transcript",
            "meeting summary",
            "AI companion",
            "meeting co-host",
            "alternative host",
        ],
        "strong_signals": [
            "zoom meetings",
            "zoom meeting",
            "meeting host",
            "meeting participant",
            "breakout rooms",
            "meeting scheduling",
            "waiting room",
            "ai companion",
            "meeting co-host",
        ],
        "medium_signals": [
            "meeting recording",
            "meeting chat",
            "meeting polls",
            "meeting reactions",
            "meeting security",
            "meeting transcript",
            "meeting summary",
            "alternative host",
        ],
        "weak_signals": [
            "meeting",
            "meetings",
            "host",
            "participant",
            "breakout",
            "scheduling",
        ],
        "negative_signals": [
            "zoom phone",
            "zoom contact center",
            "zoom rooms",
            "zoom webinar",
            "zoom clips",
            "team chat",
        ],
    },
    "zoom-rooms": {
        "name": "Zoom Rooms",
        "aliases": [
            "Zoom Rooms",
            "Zoom Room",
            "room controller",
            "room scheduling",
            "room display",
            "room calendar",
            "digital signage",
            "room sensor",
            "room analytics",
            "workspace reservation",
            "room kiosk",
            "companion whiteboard",
            "room connector",
        ],
        "strong_signals": [
            "zoom rooms",
            "zoom room",
            "room controller",
            "room scheduling",
            "digital signage",
            "workspace reservation",
            "room kiosk",
        ],
        "medium_signals": [
            "room display",
            "room calendar",
            "room sensor",
            "room analytics",
            "companion whiteboard",
            "room connector",
        ],
        "weak_signals": [
            "room",
            "rooms",
            "controller",
            "signage",
            "workspace",
            "kiosk",
        ],
        "negative_signals": [
            "zoom phone",
            "zoom contact center",
            "zoom meetings",
            "zoom webinar",
            "zoom clips",
            "breakout room",
        ],
    },
    "shared-zoom-platform": {
        "name": "Shared Zoom Platform",
        "aliases": [
            "Zoom account",
            "Zoom profile",
            "Zoom admin",
            "Zoom dashboard",
            "Zoom billing",
            "Zoom SSO",
            "Zoom security",
            "user management",
            "role management",
            "account settings",
            "Zoom mobile app",
            "Zoom desktop client",
            "Zoom web portal",
            "Zoom Marketplace",
            "Zoom notifications",
            "Zoom accessibility",
        ],
        "strong_signals": [
            "zoom account",
            "zoom admin",
            "zoom dashboard",
            "user management",
            "role management",
            "account settings",
            "sso",
            "single sign-on",
            "zoom billing",
        ],
        "medium_signals": [
            "zoom profile",
            "zoom security",
            "zoom mobile app",
            "zoom desktop client",
            "zoom web portal",
            "zoom marketplace",
            "zoom notifications",
        ],
        "weak_signals": [
            "account",
            "admin",
            "profile",
            "billing",
            "dashboard",
            "accessibility",
        ],
        "negative_signals": [],
    },
}

DEFAULT_HEADERS = {
    "User-Agent": "ZoomKB-Builder/1.0 (research project; contact: internal)",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}

MIN_BODY_LENGTH = 200
MIN_WORD_COUNT = 50
REQUEST_TIMEOUT = 30
